# Site settings
title: Jack Furr
header-img: img/linked_in.jpg
email: jackefurr@gmail.com
description: "The official blog of Jack Furr"
baseurl: ""
url: ""
linkedin_username: jackfurr
twitter_username: jackfurr
github_username:  jackfurr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gemfile", "Gemfile.lock", "Gruntfile.js","package.json","README.md"]

# Jekyll Redirect From Plugin for Redirects from Start Bootstrap Old Version
gems:
  - jekyll-paginate
  - jekyll-feed
  - rouge
